version: '2.0'

networks:
  eventbus:

services:

  redis0:
    container_name: redis0
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    working_dir: /opt/ewangplay/redis
    command: redis-server /opt/ewangplay/redis/etc/redis.conf
    ports:
      - 7001:6379
    volumes:
      - /opt/ewangplay/redis0/log:/opt/ewangplay/redis/log
      - /opt/ewangplay/redis0/data:/opt/ewangplay/redis/data
      - /opt/ewangplay/redis0/etc:/opt/ewangplay/redis/etc
    networks:
      eventbus:

  eventbus0:
    container_name: eventbus0
    image: ${EVENTBUS_IMAGE}:${EVENTBUS_TAG}
    working_dir: /opt/ewangplay/eventbus
    command: /opt/ewangplay/eventbus/bin/eventbus --config=/opt/ewangplay/eventbus/etc/eventbus.yaml
    ports:
      - 8091:8091
    volumes:
      - /opt/ewangplay/eventbus0/log:/opt/ewangplay/eventbus/log
      - /opt/ewangplay/eventbus0/data:/opt/ewangplay/eventbus/data
      - /opt/ewangplay/eventbus0/etc:/opt/ewangplay/eventbus/etc
    networks:
      eventbus:
